Create Table Artist (
id serial primary key not null,
name varchar,
song_num integer,
album_num integer );

Create Table Album (
id serial primary key not null,
name varchar,
artist varchar,
tracks integer,
year integer);

create table track (
id serial primary key not null,
song_name varchar,
album varchar,
songwriter varchar);

create table song (
id serial primary key not null,
song_name varchar,
album varchar,
songwriter varchar,
duration integer,
artist varchar);


create table songwriter (
id serial primary key not null,
name varchar);

Insert into album values
(default, 'Vanishing Vision', 'X-Japan', 9, 1988),
(default, 'Blue Blood', 'X-Japan', 12, 1989),
(default, 'Jealousy', 'X-Japan', 10, 1991),
(default, 'Art of Life', 'X-Japan', 1, 1993),
(default, 'Dahlia', 'X-Japan', 10, 1996);

Insert into album values
(default, 'Gauze', 'Dir en grey', 13, 1999),
(default, 'Macabre', 'Dir en grey', 13, 2000),
(default, 'Kisou', 'Dir en grey', 16, 2002),
(default, 'Vulgar', 'Dir en grey', 15, 2003);

Insert into artist values
(default, 'X-Japan'),
(default, 'Dir en grey');

Insert into song values
(default, 'Dear Loser', 'Vanishing Vision', 'Taiji'),
(default, 'Vanishing Love', 'Vanishing Vision', 'Yoshiki'),
(default, 'Phantom of Guilt', 'Vanishing Vision', 'Taiji'),
(default, 'Sadistic Desire', 'Vanishing Vision', 'hide'),
(default, 'Give me the Pleasure', 'Vanishing Vision', 'hide'),
(default, 'Ill Kill You', 'Vanishing Vision', 'Yoshiki'),
(default, 'Alive', 'Vanishing Vision', 'Yoshiki'),
(default, 'Kurenai', 'Vanishing Vision', 'Yoshiki'),
(default, 'Un-finished...', 'Vanishing Vision', 'Yoshiki'),
(default, 'Prologue (~World Anthem)', 'Blue Blood', 'F.Marino'),
(default, 'Blue Blood', 'Blue Blood', 'Yoshiki'),
(default, 'Week End', 'Blue Blood', 'Yoshiki'),
(default, 'Easy Fight Rambling', 'Blue Blood', 'X'),
(default, 'X', 'Blue Blood', 'Yoshiki'),
(default, 'Xclamation', 'Blue Blood', 'hide'),
(default, 'Orgasm', 'Blue Blood', 'Yoshiki'),
(default, 'Celebration', 'Blue Blood', 'hide'),
(default, 'Endless Rain', 'Blue Blood', 'Yoshiki'),
(default, 'Rose of Pain', 'Blue Blood', 'Yoshiki'),
(default, 'Kurenai Piano', 'Blue Blood', 'Yoshiki'),
(default, 'Unfinished', 'Blue Blood', 'Yoshiki'),
(default, 'Es Dur no Piano Sen', 'Jealousy', 'Yoshiki'),
(default, 'Silent Jealousy', 'Jealousy', 'Yoshiki'),
(default, 'Miscast', 'Jealousy', 'hide'),
(default, 'Desperate Angel', 'Jealousy', 'hide'),
(default, 'White Wind from Mr. Martin', 'Jealousy', 'Pata'),
(default, 'Voiceless Screaming', 'Jealousy', 'Taiji'),
(default, 'Stab me in the Back', 'Jealousy', 'Yoshiki'),
(default, 'Love Replica', 'Jealousy', 'hide'),
(default, 'Joker', 'Jealousy', 'hide'),
(default, 'Say Anything', 'Jealousy', 'Yoshiki'),
(default, 'Art of Life', 'Art of Life', 'Yoshiki'),
(default, 'Dahlia', 'Dahlia', 'Yoshiki'),
(default, 'Scars', 'Dahlia', 'hide'),
(default, 'Longing ~Togireta Melody~', 'Dahlia', 'Yoshiki'),
(default, 'Rusty Nail', 'Dahlia', 'Yoshiki'),
(default, 'White Poem I', 'Dahlia', 'Yoshiki'),
(default, 'Crucify my Love', 'Dahlia', 'Yoshiki'),
(default, 'Tears', 'Dahlia', 'Yoshiki'),
(default, 'Wriggle', 'Dahlia', 'Yoshiki'),
(default, 'Drain', 'Dahlia', 'Yoshiki'),
(default, 'Forever Love (Acoustic Version)', 'Dahlia', 'Yoshiki'),
(default, 'Gauze -Mode of Adam-', 'Gauze', 'Dir en grey'),
(default, 'Schwein no Isu', 'Gauze', 'Die'),
(default, 'Yurameki', 'Gauze', 'Shinya'),
(default, 'Raison Detre', 'Gauze', 'Toshiya'),
(default, '304-goshitsu, hakushi no sakura', 'Gauze', 'Die'),
(default, 'Cage', 'Gauze', 'Kaoru'),
(default, 'Tsumi to Batsu', 'Gauze', 'Kaoru'),
(default, 'Mazohyst of Decadance', 'Gauze', 'Kaoru'),
(default, 'Yokan', 'Gauze', 'Die'),
(default, 'Mask', 'Gauze', 'Kaoru'),
(default, 'Zan', 'Gauze', 'Kaoru'),
(default, 'Akuro no oka', 'Gauze', 'Kaoru'),
(default, 'Gauze -mode of Eve-','Gauze', 'Dir en grey'),
(default, 'Deity', 'Macabre', 'Dir en grey'),
(default, 'Myaku', 'Macabre', 'Dir en grey'),
(default, 'Wake', 'Macabre', 'Die'),
(default, 'Egnirys Cimredopyh An Injection', 'Macabre', 'Toshiya'),
(default, 'Hydra', 'Macabre', 'Kaoru'),
(default, 'Hotarubi', 'Macabre', 'Shinya'),
(default, '[KR] Cube', 'Macabre', 'Dir en grey'),
(default, 'Berry', 'Macabre', 'Kaoru'),
(default, 'Macabre', 'Macabre', 'Kaoru'),
(default, 'Audrey', 'Macabre', 'Die'),
(default, 'Rasetsukoku', 'Macabre', 'Dir en grey'),
(default, 'Zakuro', 'Macabre', 'Kaoru'),
(default, 'Taiyou no Ao', 'Macabre', 'Kaoru'),
(default, 'Kigan', 'Kisou', 'Dir en grey'),
(default, 'zomboid', 'Kisou', 'Kaoru'),
(default, '24 Cylinders', 'Kisou', 'Die'),
(default, 'Filth', 'Kisou', 'Dir en grey'),
(default, 'Bottom of the Death Valley', 'Kisou', 'Toshiya'),
(default, 'Embryo', 'Kisou', 'Kaoru'),
(default, 'Shinso', 'Kisou', 'Dir en grey'),
(default, 'Gyakujo Tanno Keloid Milk', 'Kisou', 'Kaoru'),
(default, 'Domestic Fucker Family', 'Kisou', 'Kyo'),
(default, 'Undecided', 'Kisou', 'Die'),
(default, 'Mushi', 'Kisou', 'Kaoru'),
(default, 'Shinso', 'Kisou', 'Dir en grey'),
(default, 'Jessica', 'Kisou', 'Kaoru'),
(default, 'Karasu', 'Kisou', 'Kaoru'),
(default, 'Pink Killer', 'Kisou', 'Dir en grey'),
(default, 'Shinso', 'Kisou', 'Dir en grey'),
(default, 'Audience Killer Loop', 'Vulgar', 'Dir en grey'),
(default, 'The IIID Empire', 'Vulgar', 'Dir en grey'),
(default, 'Increase Blue', 'Vulgar', 'Dir en grey'),
(default, 'Shokubeni', 'Vulgar', 'Dir en grey'),
(default, 'Sajo no uta', 'Vulgar', 'Dir en grey'),
(default, 'Red...[em]', 'Vulgar', 'Dir en grey'),
(default, 'Asunaki Koufuku, Koenaki Asu', 'Vulgar', 'Dir en grey'),
(default, 'Marmalade Chainsaw', 'Vulgar', 'Dir en grey'),
(default, 'Kasumi', 'Vulgar', 'Dir en grey'),
(default, 'R to the Core', 'Vulgar', 'Dir en grey'),
(default, 'Drain Away', 'Vulgar', 'Dir en grey'),
(default, 'New Age Culture', 'Vulgar', 'Dir en grey'),
(default, 'Obscure', 'Vulgar', 'Dir en grey'),
(default, 'Child Prey', 'Vulgar', 'Dir en grey'),
(default, 'Amber', 'Vulgar', 'Dir en grey');

 insert into songwriter values
 (default, 'Yoshiki'),
 (default, 'Taiji'),
 (default, 'hide'),
 (default, 'F. Marino'),
 (default, 'X'),
 (default, 'Pata'),
 (default, 'Dir en grey'),
 (default, 'Kyo'),
 (default, 'Kaoru'),
 (default, 'Die'),
 (default, 'Toshiya'),
 (default, 'Shinya');
 
 Insert into track values
(default, 'Dear Loser', 147, 1),
(default, 'Vanishing Love', 361, 2),
(default, 'Phantom of Guilt', 318, 3),
(default, 'Sadistic Desire', 369, 4),
(default, 'Give me the Pleasure', 177, 5),
(default, 'Ill Kill You', 179, 6),
(default, 'Alive', 509, 7),
(default, 'Kurenai', 346, 8),
(default, 'Un-finished...', 92, 9),
(default, 'Prologue (~World Anthem)', 158, 1),
(default, 'Blue Blood', 303, 2),
(default, 'Week End', 362, 3),
(default, 'Easy Fight Rambling', 283, 4),
(default, 'X', 360, 5),
(default, 'Xclamation', 222, 6),
(default, 'Orgasm', 162, 7),
(default, 'Celebration', 291, 8),
(default, 'Endless Rain', 390, 9),
(default, 'Rose of Pain', 707, 10),
(default, 'Kurenai Piano', 369, 11),
(default, 'Unfinished', 264, 12),
(default, 'Es Dur no Piano Sen', 110, 1),
(default, 'Silent Jealousy', 435, 2),
(default, 'Miscast', 312, 3),
(default, 'Desperate Angel', 348, 4),
(default, 'White Wind from Mr. Martin', 61, 5),
(default, 'Voiceless Screaming', 371, 6),
(default, 'Stab me in the Back', 234, 7),
(default, 'Love Replica', 273, 8),
(default, 'Joker', 312, 9),
(default, 'Say Anything', 520, 10),
(default, 'Art of Life', 1740, 1),
(default, 'Dahlia', 475, 1),
(default, 'Scars', 308, 2),
(default, 'Longing ~Togireta Melody~', 462, 3),
(default, 'Rusty Nail', 327, 4),
(default, 'White Poem I', 196, 5),
(default, 'Crucify my Love', 270, 6),
(default, 'Tears', 630, 7),
(default, 'Wriggle', 84, 8),
(default, 'Drain', 202, 9),
(default, 'Forever Love (Acoustic Version)', 474, 10),
(default, 'Gauze -Mode of Adam-', 127, 1),
(default, 'Schwein no Isu', 211, 2),
(default, 'Yurameki', 305, 3),
(default, 'Raison Detre', 288, 4),
(default, '304-goshitsu, hakushi no sakura', 318, 5),
(default, 'Cage', 335, 6),
(default, 'Tsumi to Batsu', 308, 7),
(default, 'Mazohyst of Decadance', 562, 8),
(default, 'Yokan', 279, 9),
(default, 'Mask', 265, 10),
(default, 'Zan', 303, 11),
(default, 'Akuro no oka', 582, 12),
(default, 'Gauze -mode of Eve-',4, 13),
(default, 'Deity', 255, 1),
(default, 'Myaku', 245, 2),
(default, 'Wake', 312, 3),
(default, 'Egnirys Cimredopyh An Injection', 316, 4),
(default, 'Hydra', 341, 5),
(default, 'Hotarubi', 306, 6),
(default, '[KR] Cube', 249, 7),
(default, 'Berry', 260, 8),
(default, 'Macabre', 649, 9),
(default, 'Audrey', 273, 10),
(default, 'Rasetsukoku', 215, 11),
(default, 'Zakuro', 517, 12),
(default, 'Taiyou no Ao', 379, 13),
(default, 'Kigan', 244, 1),
(default, 'zomboid', 262, 2),
(default, '24 Cylinders', 367, 3),
(default, 'Filth', 295, 4),
(default, 'Bottom of the Death Valley', 350, 5),
(default, 'Embryo', 336, 6),
(default, 'Shinso', 125, 7),
(default, 'Gyakujo Tanno Keloid Milk', 282, 8),
(default, 'Domestic Fucker Family', 182, 9),
(default, 'Undecided', 293, 10),
(default, 'Mushi', 384, 11),
(default, 'Shinso', 57, 12),
(default, 'Jessica', 251, 13),
(default, 'Karasu', 326, 14),
(default, 'Pink Killer', 228, 15),
(default, 'Shinso', 183, 16),
(default, 'Audience Killer Loop', 189, 1),
(default, 'The IIID Empire', 185, 2),
(default, 'Increase Blue', 226, 3),
(default, 'Shokubeni', 260, 4),
(default, 'Sajo no uta', 194, 5),
(default, 'Red...[em]', 301, 6),
(default, 'Asunaki Koufuku, Koenaki Asu', 211, 7),
(default, 'Marmalade Chainsaw', 253, 8),
(default, 'Kasumi', 260, 9),
(default, 'R to the Core', 107, 10),
(default, 'Drain Away', 246, 11),
(default, 'New Age Culture', 199, 12),
(default, 'Obscure', 239, 13),
(default, 'Child Prey', 232, 14),
(default, 'Amber', 288, 15);